### ISSUE TITLE
On IE11 images are not visible

### ISSUE THREAD

**Issue by emilioSp** [italia/cloud.italia.it-site#95]

**Comment by pietro909** [comment]
I could observe it in Browserstack (IE 11 on Windows 10): the images do load blurried but then disappear.
Using `position: static` on the `<picture>` element fixes it, but it is added by `gatsby-plugin-image` and I have zero knowledge of Gatsby's plugins :-) maybe someone else knows how to pass down conditional styling?

<img width="1442" alt="Screenshot 2021-05-06 at 14 29 20" src="https://user-images.githubusercontent.com/2094604/117298875-254c5480-ae78-11eb-949c-1b4de790aa90.png">
